export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_ERRORS = "SET_ERRORS";
export const FETCH_CHANNELS = "FETCH_CHANNELS";
export const CREATE_CHANNELS = "CREATE_CHANNELS";
export const FETCH_CHANNEL_MESSAGE = "FETCH_CHANNEL_MESSAGE";
export const POST_CHANNEL_MESSAGE = "POST_CHANNEL_MESSAGE";
export const FETCH_MESSAGE_BY_TIME_STAMP = "FETCH_MESSAGE_BY_TIME_STAMP";
export const JOIN_CHANNEL = "JOIN_CHANNEL";
